# Generated by Django 6.0.6 on 2026-07-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='divinationsession',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
