# Generated by Django 6.0.6 on 2026-07-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0002_remove_legacy_message_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='True for the initial interpret prompt/reply, hidden from chat history.'),
        ),
    ]
